### ISSUE TITLE
Tooltip is too far left

### ISSUE THREAD

**Issue by solomon23** [ryu1kn/vscode-annotator#10]
![screen shot 2016-10-10 at 6 05 16 pm](https://cloud.githubusercontent.com/assets/857744/19255570/32b95a7e-8f14-11e6-8424-54f8b4603d2d.png)

The tooltip covers the gutter so you can't click the commit

VSC 1.6.0

**Comment by ryu1kn** [comment]
Oh wow, yup it's happening on my mac too. Thanks for reporting it.

**Comment by ryu1kn** [comment]
I can reproduce the problem by opening a html that Annotator generates with Chrome 53. On Safari, the html is displayed correctly. So I wonder if it's caused by Chrome update (VS Code v1.6 updated it's Electron version)

> ## Electron update
> 
> In this release, we decided to take a major update of the Electron framework. We now run with version 1.3.7 which brings big version increments to the Chrome rendering engine (from 49 to 52) and ...

https://code.visualstudio.com/updates/v1_6

**Comment by ryu1kn** [comment]
Published as v0.10.1

**Comment by ryu1kn** [comment]
Oops! I fixed on vscode v1.6 but broke on v1.5 or below. Tooltip goes far right.

![tooltip-go-far-right-with-below-vsc-v1_6](https://cloud.githubusercontent.com/assets/1505715/19268297/6d00c03c-8fff-11e6-90a0-b707db8d357c.png)

For those who are using vscode v1.5 but updated your Annotator to v0.10.1, please update your vscode to v1.6. If you can't do it, please let me know then I'll think about applying a fix for v1.5. But usually we just upgrade our vscode once it becomes available, I hope...
