### ISSUE TITLE
How to toggle off?

### ISSUE THREAD

**Issue by seanknox** [ryu1kn/vscode-annotator#13]
Hi there, cool plugin. How do I toggle the annotations off once enabled?

**Comment by ryu1kn** [comment]
Hi seankox. Doesn't disabling on extension view work?

https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension

**Comment by seanknox** [comment]
Disabling the extension entirely works of course. Is there no toggle built
in to the extension?

**Comment by ryu1kn** [comment]
Ah, do you mean toggling off the annotations on an annotation view?

It's not that Annotator opens an annotation column in your editing view, but it opens a separate html view with annotations and your code; so after you checked the annotations, you can close off the annotation tab.

**Comment by seanknox** [comment]
Now I understand. Thanks!
