### ISSUE TITLE
spawn git ENOENT when annotate on current file

### ISSUE THREAD

**Issue by chidov** [ryu1kn/vscode-annotator#14]
I have a private git repo and when i try to annotate it. it show spawn git ENOENT.

![image](https://user-images.githubusercontent.com/5102972/31478783-68dc5892-aed8-11e7-91b1-a172c268e4e8.png)

**Comment by chidov** [comment]
fixed when i put git.path in setting.json, i am using windows

**Comment by ryu1kn** [comment]
So I can close this I think?
