### ISSUE TITLE
Add option to use git blame -w (ignore whitespace)

### ISSUE THREAD

**Issue by momoking** [ryu1kn/vscode-annotator#15]
The left pane of annotator always gives me:

> Commit: 0000000000000000000000000000000000000000
> Author: Not Committed Yet

If I execute `git blame`, it shows the same thing. (So it's not a plugin issue).

If I execute `git blame -w`, then it shows the correct commit history. This is because I'm working on a Windows machine (CRLF), and the code on repo is on Linux (LF). (The -w option ignores the whitespace)

Could you provide an option in plugin to use `git blame -w`?

Thank you

**Comment by ryu1kn** [comment]
Hi @momoking , thank you for suggesting an improvement and checking git blame behaviours on both console and annotator! That makes my job a lot easier!!

Yes, your use case should be definitely covered 👍

**Comment by ryu1kn** [comment]
Released as v0.11.0! 👍
