### ISSUE TITLE
vscode.previewHtml depricated

### ISSUE THREAD

**Issue by sarabkohli29** [ryu1kn/vscode-annotator#17]
While trying to open annotater from the vscode command prompt on vscode Version 1.33.0 (1.33.0), the annotater is not able to open the diff file and ends upthrowing a console error
![Screen Shot 2019-04-10 at 8 54 05 PM](https://user-images.githubusercontent.com/10605794/55929720-cfdae600-5bd2-11e9-8c6d-1c0a468b219a.png)

Reading the vscode docs, it mentions that the vscode.previewHtml has been completely been depricated here https://github.com/Microsoft/vscode/issues/62630 in the March/April release and instead the webview api should be used. https://code.visualstudio.com/api/extension-guides/webview

I am on MacOS Mojave version 10.14.4 MBP-15 2018 version

**Comment by ryu1kn** [comment]
Thanks @sarabkohli29 for reporting it and sorry for the inconvenience.
I guess Annotator is not very popular Git blame plugin anymore and people are using other options. Maybe you want to check them on Code's marketplace.

https://marketplace.visualstudio.com/search?term=git%20blame&target=VSCode&category=All%20categories&sortBy=Relevance

Meanwhile, I'll fix this issue when I find a time.

**Comment by timwaddell** [comment]
This is my favourite blame tool .. nothing else gives a complete file overview
Would be great if this was fixed :)

**Comment by ryu1kn** [comment]
I need to do something like this change I made for my other extension.

https://github.com/ryu1kn/vscode-extension-update-reporter/commit/2d80e7ec45707bd64093c439d5e57f9e2c1f097d

**Comment by ryu1kn** [comment]
When I hit Annotator command, it doesn't show an error popup dialog, it just gets logged on the dev-tool console as @sarabkohli29 kindly posted the screenshot... If there's no error popup, it's confusing :(

**Comment by ryu1kn** [comment]
Does WebView panel not support `command:` link like below? Do I have to replace this with other mechanism? 😑

```html
<a href="command:annotator.takeDiff?%5B%7B...">12  2018-12-24 Ryuichi Inagaki</a>
```

**Comment by ryu1kn** [comment]
Like this?

* [Passing messages from a webview to an extension](https://code.visualstudio.com/api/extension-guides/webview#passing-messages-from-a-webview-to-an-extension)

**Comment by sarabkohli29** [comment]
Wow, it's coming together. Seems like you already got most of the things. Thank you for fixing this. I was about try my first open source PR to make those changes, but since I am new to this, I wasn't able to fully grasp the API. Seems you've figured out all the things needed. Just to mention, webview api should be able to support HTML, so the `<a>` links should technically work if the `panel.webview.html` contains those links, but after looking at your comment above, I think it might have some issues.

**Comment by ryu1kn** [comment]
Hi @sarabkohli29 ! Wow, I didn't know that you were considering to fix this, thank you 😊 I've already started this one, but if there are other things, your help is much appreciated!

Re webview panel, yes, that's what I thought too. I played with `<a>` last night for a while. If I put a link to google website, I could open the site by clicking annotation, but it didn't work if I put a `command:annotator.takeDiff` command as I was doing in `previewHtml`.

**Comment by ryu1kn** [comment]
Oops, my bad! It's actually I just have to pass `enableCommandUris: true` on creating a WebView panel!

https://code.visualstudio.com/api/references/vscode-api#WebviewOptions

**Comment by ryu1kn** [comment]
Ref https://github.com/Microsoft/vscode/issues/62630

**Comment by ryu1kn** [comment]
Thank you @sarabkohli29 and @timwaddell for reporting this! and sorry for the inconvenience caused! The fix is released as v0.11.1 🎉

**Comment by sarabkohli29** [comment]
Actually, thank you @ryu1kn for fixing this! :)

**Comment by timwaddell** [comment]
thank you :)
