### ISSUE TITLE
[feat] Close annotate

### ISSUE THREAD

**Issue by millionhari** [ryu1kn/vscode-annotator#19]
Implement a command to close the annotate sidebar. Currently only able to open the annotate sidebar, but can't close it.

**Comment by purplejacket** [comment]
omg, +1000 for this feature request, thanks.

**Comment by ryu1kn** [comment]
Hello. The annotation sidebar is actually not opened on your editing view, Annotator opens a completely new html view with the git blame information; so we can't just close the annotation column...

cf. https://github.com/ryu1kn/vscode-annotator/issues/13

**Comment by purplejacket** [comment]
Ok.  I forked the repo and updated the README to give the user a little more clarity.  Feel free to merge it if you like.
https://github.com/purplejacket/vscode-annotator/tree/master
or
https://github.com/purplejacket/vscode-annotator/tree/purplejacket-patch-readme

**Comment by ryu1kn** [comment]
Thanks @purplejacket , I merged your documentation update 👍
