### ISSUE TITLE
Syntax highlighting in diff view

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-annotator#3]

**Comment by ryu1kn** [comment]
It looks if I provide a file name (with extension) to the path of a URI, I can let the editor to understand a file type

**Comment by basdek** [comment]
Big plus one on this one, would make the plugin much more useful! Thanks!

**Comment by ryu1kn** [comment]
@basdek Syntax highlighting is already there on the diff view (if not, let me know). Did you actually mean the annotation view? That's not done yet and the issue #1 is for it?
