### ISSUE TITLE
Failure to find git 

### ISSUE THREAD

**Issue by zabel-xyz** [ryu1kn/vscode-annotator#6]
If Git is not in PATH (environment variable), it doesn't work.
Could you use the same principle as the extension `gitHistoryVSCode`to determine Git Path ?
(https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/helpers/historyUtils.ts)

Thank you

**Comment by ryu1kn** [comment]
Hi, thanks for your suggestion. I should respect `git.path` value in the editor settings.
As for the part reading a git path from Windows registry, I don't think I'll do it as that seems to be for only one particular git client (Git for Windows).

**Comment by ryu1kn** [comment]
Found this on VS Code's page. Annotator should also find git command either from `git.path` or from `PATH`

> Q: I have GitHub Desktop installed on my computer but VS Code ignores it.
> 
> A: VS Code expects git.exe to be on the operating system's PATH ($PATH on OS X or Linux). GitHub Desktop installs isolated git binaries and does not automatically add git.exe to PATH.
> 
> You can either:
> - Add the location of git.exe to PATH and restart VS Code.
> - Set the git.path setting to the location of git.exe.

https://code.visualstudio.com/docs/editor/versioncontrol#_common-questions

**Comment by ryu1kn** [comment]
Published as v0.7.3 :)
