### ISSUE TITLE
Error when there is no blame

### ISSUE THREAD

**Issue by zabel-xyz** [ryu1kn/vscode-annotator#7]
When there is no blame (not yet in git) I have the following error:
![image](https://cloud.githubusercontent.com/assets/16486407/17341284/261c8648-58f4-11e6-8128-f0e4ebc2449f.png)

**Comment by ryu1kn** [comment]
Thanks for posting the screenshot, that's very helpful to understand the issue ;)
And yes, "git command finished with non-zero" isn't really helpful. It should say something like, not tracked by git.

**Comment by ryu1kn** [comment]
Published the fix as v0.10.0 :)
