### ISSUE TITLE
Selectable popover text

### ISSUE THREAD

**Issue by Yukaii** [ryu1kn/vscode-annotator#8]
Currently commit popover text is not selectable, but sometimes I want to copy the commit hash id or commit message. Is it possible in current VSCode API?

**Comment by ryu1kn** [comment]
Annotation view is composed as HTML and the popover is using a pseudo element. As we cannot select a text in a pseudo element, to make it possible I need to come up with a new way. Hmm...

**Comment by ryu1kn** [comment]
Converted the popover to a non-pseudo element.
Just published as v0.9.0, closing this issue now.

**Comment by Yukaii** [comment]
Thanks a lot!

**Comment by ryu1kn** [comment]
No worries. Thanks for the suggestion ;)
